import{i as g,S as L}from"./assets/vendor-9310f15c.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const l=document.querySelector(".gallery"),s=document.getElementById("loader"),w=document.getElementById("search-form"),b=document.getElementById("load-more"),m=document.getElementById("loading-indicator"),I="42175181-9f2e4ea0c75ffabf50c3ef9f9";let a=1,u="",B=0;function f(e){g.success({title:"Success",message:e,position:"topRight"})}function i(e){g.error({title:"Error",message:e,position:"topRight"})}async function y(e,n=1){const t=`https://pixabay.com/api/?key=${I}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`;return(await(await fetch(t)).json()).hits}w.addEventListener("submit",async function(e){e.preventDefault(),toggleLoadMoreBtn(!1);const n=document.getElementById("query").value.trim();if(!n){g.warning({title:"Warning",message:"Search images..."});return}try{s.style.display="block",u=n,a=1;const t=await y(n,a);t.length>0?(v(t),f(`Was found: ${t.length} images`),p(),showBtn()):(l.innerHTML="",i("Sorry, there are no images matching your search query. Please try again!"),hideBtn())}catch(t){console.error("Error fetching images:",t),i("Failed to fetch images.")}finally{s.style.display="none"}});b.addEventListener("click",async function(){try{s.style.display="block",m.style.display="block",a++;const e=await y(u,a);e.length>0?(h(e),f(`Loaded additional ${e.length} images`),p(),e.length<15&&(i("No more images to load"),hideBtn()),$()):(i("No more images to load"),hideBtn())}catch(e){console.error("Error fetching images:",e),i("Failed to fetch additional images.")}finally{s.style.display="none",m.style.display="none"}});function $(){const n=l.querySelector(".image-card").getBoundingClientRect().height*2;window.scrollBy({top:n,behavior:"smooth"})}function v(e){l.innerHTML="",h(e)}function h(e){const n=e.map(t=>`
            <div class="image-card">
                <a href="${t.largeImageURL}" data-lightbox="image-set" data-title="${t.tags}">
                    <img src="${t.webformatURL}" alt="${t.tags}">
                    <div class="info">Likes: ${t.likes}, Views: ${t.views}, Comments: ${t.comments}, Downloads: ${t.downloads}</div>
                </a>
            </div>
        `);l.innerHTML+=n.join(""),B+=e.length}function p(){new L(".gallery a").refresh()}
//# sourceMappingURL=commonHelpers.js.map
